# Generated by Django 5.0.7 on 2025-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_group_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
