# Generated by Django 5.0.7 on 2025-07-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_is_completed_task_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
